import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  8453: {
    MostClawdWanted: {
      address: "0xDC03A2B68b56dF719aE1f51930bb790e33aDe595",
      abi: [
        {
          type: "constructor",
          inputs: [{ name: "initialOwner", type: "address", internalType: "address" }],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "BPS_DENOMINATOR",
          inputs: [],
          outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "BURN_ADDRESS",
          inputs: [],
          outputs: [{ name: "", type: "address", internalType: "address" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "CLAWD",
          inputs: [],
          outputs: [{ name: "", type: "address", internalType: "contract IERC20" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_BURN_BPS",
          inputs: [],
          outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MAX_TREASURY_BPS",
          inputs: [],
          outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "MIN_CLAIMANT_BPS",
          inputs: [],
          outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "TREASURY",
          inputs: [],
          outputs: [{ name: "", type: "address", internalType: "address" }],
          stateMutability: "view",
        },
        { type: "function", name: "acceptOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
        {
          type: "function",
          name: "approve",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "claimant", type: "address", internalType: "address" },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "bounties",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [
            { name: "id", type: "uint256", internalType: "uint256" },
            { name: "creator", type: "address", internalType: "address" },
            { name: "descriptionCID", type: "string", internalType: "string" },
            { name: "createdAt", type: "uint256", internalType: "uint256" },
            { name: "deadline", type: "uint256", internalType: "uint256" },
            { name: "totalPledged", type: "uint256", internalType: "uint256" },
            { name: "status", type: "uint8", internalType: "enum MostClawdWanted.BountyStatus" },
            { name: "resolutionMode", type: "uint8", internalType: "enum MostClawdWanted.ResolutionMode" },
            { name: "judge", type: "address", internalType: "address" },
            { name: "judgeNominationTime", type: "uint256", internalType: "uint256" },
            { name: "judgeVetoWindow", type: "uint256", internalType: "uint256" },
            { name: "claimMode", type: "uint8", internalType: "enum MostClawdWanted.ClaimMode" },
            { name: "currentClaimant", type: "address", internalType: "address" },
            { name: "claimWindow", type: "uint256", internalType: "uint256" },
            { name: "refundPolicy", type: "uint8", internalType: "enum MostClawdWanted.RefundPolicy" },
            { name: "refundUnlockTime", type: "uint256", internalType: "uint256" },
            { name: "claimantBps", type: "uint16", internalType: "uint16" },
            { name: "treasuryBps", type: "uint16", internalType: "uint16" },
            { name: "burnBps", type: "uint16", internalType: "uint16" },
            { name: "pledgerOverrideBps", type: "uint16", internalType: "uint16" },
            { name: "challengeWindow", type: "uint256", internalType: "uint256" },
            { name: "resolvedClaimant", type: "address", internalType: "address" },
            { name: "finalizedAt", type: "uint256", internalType: "uint256" },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "bountyCount",
          inputs: [],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "cancelBounty",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claim",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "claimantAt",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "i", type: "uint256", internalType: "uint256" },
          ],
          outputs: [{ name: "", type: "address", internalType: "address" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claimantCount",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "claimants",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "claimant", type: "address", internalType: "address" },
          ],
          outputs: [
            { name: "hasClaimed", type: "bool", internalType: "bool" },
            { name: "hasSubmitted", type: "bool", internalType: "bool" },
            { name: "approved", type: "bool", internalType: "bool" },
            { name: "rejected", type: "bool", internalType: "bool" },
            { name: "claimDeadline", type: "uint256", internalType: "uint256" },
            { name: "proofCID", type: "string", internalType: "string" },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "createBounty",
          inputs: [
            { name: "descriptionCID", type: "string", internalType: "string" },
            { name: "deadline", type: "uint256", internalType: "uint256" },
            { name: "resolutionMode", type: "uint8", internalType: "enum MostClawdWanted.ResolutionMode" },
            { name: "judge", type: "address", internalType: "address" },
            { name: "judgeVetoWindow", type: "uint256", internalType: "uint256" },
            { name: "claimMode", type: "uint8", internalType: "enum MostClawdWanted.ClaimMode" },
            { name: "claimWindow", type: "uint256", internalType: "uint256" },
            { name: "refundPolicy", type: "uint8", internalType: "enum MostClawdWanted.RefundPolicy" },
            { name: "refundUnlockTime", type: "uint256", internalType: "uint256" },
            { name: "claimantBps", type: "uint16", internalType: "uint16" },
            { name: "treasuryBps", type: "uint16", internalType: "uint16" },
            { name: "burnBps", type: "uint16", internalType: "uint16" },
            { name: "pledgerOverrideBps", type: "uint16", internalType: "uint16" },
            { name: "challengeWindow", type: "uint256", internalType: "uint256" },
          ],
          outputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "expireBounty",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "expireClaim",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "finalize",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getClaimantInfo",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "claimant", type: "address", internalType: "address" },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct MostClawdWanted.ClaimantInfo",
              components: [
                { name: "hasClaimed", type: "bool", internalType: "bool" },
                { name: "hasSubmitted", type: "bool", internalType: "bool" },
                { name: "approved", type: "bool", internalType: "bool" },
                { name: "rejected", type: "bool", internalType: "bool" },
                { name: "claimDeadline", type: "uint256", internalType: "uint256" },
                { name: "proofCID", type: "string", internalType: "string" },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "hasVoted",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "voter", type: "address", internalType: "address" },
          ],
          outputs: [{ name: "voted", type: "bool", internalType: "bool" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "judgeVetoWeight",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [{ name: "weight", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "lastVetoNomination",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "voter", type: "address", internalType: "address" },
          ],
          outputs: [{ name: "nominationTime", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "nominateJudge",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [{ name: "", type: "address", internalType: "address" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pendingOwner",
          inputs: [],
          outputs: [{ name: "", type: "address", internalType: "address" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "pledge",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "amount", type: "uint256", internalType: "uint256" },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "pledges",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "pledger", type: "address", internalType: "address" },
          ],
          outputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "refund",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "reject",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "claimant", type: "address", internalType: "address" },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "rejectWeights",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "candidate", type: "address", internalType: "address" },
          ],
          outputs: [{ name: "rejectWeight", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        { type: "function", name: "renounceOwnership", inputs: [], outputs: [], stateMutability: "nonpayable" },
        {
          type: "function",
          name: "submitProof",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "proofCID", type: "string", internalType: "string" },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "vetoJudge",
          inputs: [{ name: "bountyId", type: "uint256", internalType: "uint256" }],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "voteResolve",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "candidate", type: "address", internalType: "address" },
            { name: "approve_", type: "bool", internalType: "bool" },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "voteWeights",
          inputs: [
            { name: "bountyId", type: "uint256", internalType: "uint256" },
            { name: "candidate", type: "address", internalType: "address" },
          ],
          outputs: [{ name: "voteWeight", type: "uint256", internalType: "uint256" }],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "Approved",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "claimant", type: "address", indexed: true, internalType: "address" },
            { name: "judge", type: "address", indexed: true, internalType: "address" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BountyCreated",
          inputs: [
            { name: "id", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "creator", type: "address", indexed: true, internalType: "address" },
            { name: "descriptionCID", type: "string", indexed: false, internalType: "string" },
            { name: "deadline", type: "uint256", indexed: false, internalType: "uint256" },
            {
              name: "resolutionMode",
              type: "uint8",
              indexed: false,
              internalType: "enum MostClawdWanted.ResolutionMode",
            },
            { name: "claimMode", type: "uint8", indexed: false, internalType: "enum MostClawdWanted.ClaimMode" },
            { name: "refundPolicy", type: "uint8", indexed: false, internalType: "enum MostClawdWanted.RefundPolicy" },
            { name: "claimantBps", type: "uint16", indexed: false, internalType: "uint16" },
            { name: "treasuryBps", type: "uint16", indexed: false, internalType: "uint16" },
            { name: "burnBps", type: "uint16", indexed: false, internalType: "uint16" },
            { name: "challengeWindow", type: "uint256", indexed: false, internalType: "uint256" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "BountyExpired",
          inputs: [{ name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" }],
          anonymous: false,
        },
        {
          type: "event",
          name: "BountyExpiredClaim",
          inputs: [{ name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" }],
          anonymous: false,
        },
        {
          type: "event",
          name: "Cancelled",
          inputs: [{ name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" }],
          anonymous: false,
        },
        {
          type: "event",
          name: "Claimed",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "claimant", type: "address", indexed: true, internalType: "address" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Finalized",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "winner", type: "address", indexed: true, internalType: "address" },
            { name: "claimantAmount", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "treasuryAmount", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "burnAmount", type: "uint256", indexed: false, internalType: "uint256" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JudgeNominated",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "judge", type: "address", indexed: true, internalType: "address" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JudgeVetoRegistered",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "voter", type: "address", indexed: true, internalType: "address" },
            { name: "weight", type: "uint256", indexed: false, internalType: "uint256" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "JudgeVetoed",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "previousJudge", type: "address", indexed: true, internalType: "address" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferStarted",
          inputs: [
            { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            { name: "previousOwner", type: "address", indexed: true, internalType: "address" },
            { name: "newOwner", type: "address", indexed: true, internalType: "address" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Pledged",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "pledger", type: "address", indexed: true, internalType: "address" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
            { name: "totalPledged", type: "uint256", indexed: false, internalType: "uint256" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ProofSubmitted",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "claimant", type: "address", indexed: true, internalType: "address" },
            { name: "proofCID", type: "string", indexed: false, internalType: "string" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Refunded",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "pledger", type: "address", indexed: true, internalType: "address" },
            { name: "amount", type: "uint256", indexed: false, internalType: "uint256" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Rejected",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "claimant", type: "address", indexed: true, internalType: "address" },
            { name: "judge", type: "address", indexed: true, internalType: "address" },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "Voted",
          inputs: [
            { name: "bountyId", type: "uint256", indexed: true, internalType: "uint256" },
            { name: "voter", type: "address", indexed: true, internalType: "address" },
            { name: "candidate", type: "address", indexed: true, internalType: "address" },
            { name: "approve", type: "bool", indexed: false, internalType: "bool" },
            { name: "weight", type: "uint256", indexed: false, internalType: "uint256" },
          ],
          anonymous: false,
        },
        { type: "error", name: "AlreadyClaimed", inputs: [] },
        { type: "error", name: "AlreadyResolved", inputs: [] },
        { type: "error", name: "AlreadySubmitted", inputs: [] },
        { type: "error", name: "AlreadyVoted", inputs: [] },
        { type: "error", name: "BountyNotClaimed", inputs: [] },
        { type: "error", name: "BountyNotOpen", inputs: [] },
        { type: "error", name: "ChallengeWindowNotOver", inputs: [] },
        { type: "error", name: "ClaimWindowExpired", inputs: [] },
        { type: "error", name: "DeadlineNotPassed", inputs: [] },
        { type: "error", name: "DeadlinePassed", inputs: [] },
        { type: "error", name: "InvalidAmount", inputs: [] },
        { type: "error", name: "InvalidBurnBps", inputs: [] },
        { type: "error", name: "InvalidChallengeWindow", inputs: [] },
        { type: "error", name: "InvalidClaimMode", inputs: [] },
        { type: "error", name: "InvalidClaimantBps", inputs: [] },
        { type: "error", name: "InvalidDeadline", inputs: [] },
        { type: "error", name: "InvalidJudgeVetoWindow", inputs: [] },
        { type: "error", name: "InvalidPledgerOverrideBps", inputs: [] },
        { type: "error", name: "InvalidResolutionMode", inputs: [] },
        { type: "error", name: "InvalidSplits", inputs: [] },
        { type: "error", name: "InvalidTreasuryBps", inputs: [] },
        { type: "error", name: "JudgeIsClaimant", inputs: [] },
        { type: "error", name: "JudgeNotSet", inputs: [] },
        { type: "error", name: "JudgeSlotTaken", inputs: [] },
        { type: "error", name: "JudgeVetoWindowActive", inputs: [] },
        { type: "error", name: "JudgeVetoWindowExpired", inputs: [] },
        { type: "error", name: "NoApprovedClaimant", inputs: [] },
        { type: "error", name: "NotClaimant", inputs: [] },
        { type: "error", name: "NotCreator", inputs: [] },
        { type: "error", name: "NotJudge", inputs: [] },
        { type: "error", name: "NotPledger", inputs: [] },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [{ name: "owner", type: "address", internalType: "address" }],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [{ name: "account", type: "address", internalType: "address" }],
        },
        { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
        { type: "error", name: "RefundNotAvailable", inputs: [] },
        {
          type: "error",
          name: "SafeERC20FailedOperation",
          inputs: [{ name: "token", type: "address", internalType: "address" }],
        },
        { type: "error", name: "ZeroAddress", inputs: [] },
      ] as const,
      inheritedFunctions: {},
    },
  },
} as const satisfies GenericContractsDeclaration;

export default deployedContracts;
